package com.prwatech.skillama.script;

import com.prwatech.skillama.model.EvaluationQuestion;
import com.prwatech.skillama.repository.EvaluationQuestionRepository;
import com.prwatech.skillama.util.IndiaTime;
import lombok.AllArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Seeds the default Tester evaluation question bank on first startup, so the
 * evaluation modal isn't empty before an admin configures anything. Idempotent:
 * only seeds when the collection is empty — never overwrites admin edits/deletes
 * made afterward.
 */
@Component
@AllArgsConstructor
public class EvaluationQuestionSeedScript implements CommandLineRunner {

    private static final Logger LOGGER = LoggerFactory.getLogger(EvaluationQuestionSeedScript.class);

    private final EvaluationQuestionRepository questionRepository;

    @Override
    public void run(String... args) {
        try {
            if (questionRepository.count() > 0) {
                LOGGER.info("Evaluation questions already exist. Skipping default seed.");
                return;
            }

            LOGGER.info("No evaluation questions found. Seeding default question bank...");
            List<EvaluationQuestion> defaults = List.of(
                    question(EvaluationQuestion.Category.CONTENT, 1,
                            "Does the answer explain the topic clearly and accurately?"),
                    question(EvaluationQuestion.Category.CONTENT, 2,
                            "Is the explanation too detailed (overexplained) or too brief (underexplained)?"),
                    question(EvaluationQuestion.Category.CONTENT, 3,
                            "Does the response include any irrelevant or off-topic information?"),
                    question(EvaluationQuestion.Category.IMAGE, 1,
                            "Is the image relevant to the content explained by the AI?"),
                    question(EvaluationQuestion.Category.IMAGE, 2,
                            "Is the image relevant to the topic itself?"),
                    question(EvaluationQuestion.Category.IMAGE, 3,
                            "If the topic is practical in nature, does the image accurately represent the practical example?"),
                    question(EvaluationQuestion.Category.PRACTICAL, 1,
                            "Does the practical content (for example, the code execution window) match the explanation provided by the AI?"),
                    question(EvaluationQuestion.Category.PRACTICAL, 2,
                            "Does the output generated by the code match the code shown in the practical example?"));

            questionRepository.saveAll(defaults);
            LOGGER.info("Seeded {} default evaluation questions.", defaults.size());
        } catch (Exception e) {
            LOGGER.error("Error seeding default evaluation questions: {}", e.getMessage(), e);
        }
    }

    private EvaluationQuestion question(EvaluationQuestion.Category category, int order, String text) {
        return EvaluationQuestion.builder()
                .category(category)
                .questionText(text)
                .order(order)
                .active(true)
                .createdAt(IndiaTime.now())
                .updatedAt(IndiaTime.now())
                .createdBy("SYSTEM")
                .updatedBy("SYSTEM")
                .build();
    }
}
